### ISSUE TITLE
Semantic issue

### ISSUE THREAD

**Issue by cichy** [7kfpun/FinanceMacOSReactNative#1]
<img width="381" alt="zrzut ekranu 2016-11-07 o 11 33 45" src="https://cloud.githubusercontent.com/assets/443253/20054690/4a7ab6be-a4de-11e6-9056-b6eecac287b0.png">

**Comment by 7kfpun** [comment]
You need Xcode 8.1 on macOS Sierra 10.12.1 (12B2657) or later.

**Comment by cichy** [comment]
Thanks mate.
